### ISSUE TITLE
Exports in package.json files should start with ./

### ISSUE THREAD

**Issue by lajoiemedia** [WHenderson/stores-mono#10]
I get the following error when I build with vite on the server side.

Error (lightly edited to remove private info):
```
ERROR  Invalid "exports" main target "dist/index.mjs" defined in the package config node_modules/@crikey/stores-temporal/package.json imported from server.mjs; targets must start with "./"
```

Going into `node_modules/@crikey/*/package.json` and changing all the "exports" from `dist/index.mjs` to `./dist/index.mjs` fixes it.

**Comment by WHenderson** [comment]
Thanks for the report.

I've made the updates you suggested. Let me know if it resolves your issues.
