### ISSUE TITLE
For packages with .mjs modules, types must be exported as .d.mts files

### ISSUE THREAD

**Issue by FunkMonkey** [WHenderson/stores-mono#11]
I am getting this error

> Could not find a declaration file for module '@crikey/stores-strict'. '[...]/node_modules/@crikey/stores-strict/dist/index.mjs' implicitly has an 'any' type.
>  There are types at '[...]/node_modules/@crikey/stores-strict/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@crikey/stores-strict' library may need to update its package.json or typings.ts(7016)

This apparently happens because I use `modeResolution: "bundler"` in my tsconfig.

Looking at this [typescript issue](https://github.com/microsoft/TypeScript/issues/52363) it seems that for `.mjs` modules, the relevant type information must reside in a `.d.mts` file.

I tried it out by renaming `index.d.ts` to `index.d.mts` and changing `package.json` accordingly and everything works as expected then.

Thank you very much!

**Comment by FunkMonkey** [comment]
p.s. alternatively, in case simply altering the `package.json` to `"typings": "index.d.mts` breaks non-es6 modules (`main`), you could create proper exports for typings, similar to [this post](https://github.com/microsoft/TypeScript/issues/52363#issuecomment-1659179354).

**Comment by FunkMonkey** [comment]
I think this change to the `package.json` files should work for all cases:

```json
  "exports": {
    "import": {
      "types": "./dist/index.d.ts",
      "default": "./dist/index.mjs"
    },
    "require": {
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js"
    }
  },
```

**Comment by WHenderson** [comment]
Validating if you've setup your package.json files should be easier than this :-/

I'll make a release with your suggested changes and we can find out if it works. I'm pretty tied up at the moment though, feel free to submit a pull request if you are in a rush.

**Comment by FunkMonkey** [comment]
@WHenderson Alright, I created a pull request!

> Validating if you've setup your package.json files correctly should be easier than this :-/

Not sure what you mean here. What could be misconfigured in my package.json so that TS complains in this way?

**Comment by WHenderson** [comment]
Sorry, when I said "Validating you've..." I didn't mean you @FunkMonkey, I meant the [generic you](https://en.wikipedia.org/wiki/Generic_you). I was complaining that validating my work when I first did it was a pain and I apparently missed something which has now caused issues.

I'm still pretty tied up for the next couple weeks though as I'm doing two releases and the final change requests. (hence me responding at 10:30pm)

**Comment by FunkMonkey** [comment]
> I was complaining that validating my work when I first did it was a pain and I apparently missed something which has now caused issues.

I totally understand this feeling. The only constant in web development is change.
I guess for testing this specific problem, one would need some test-packages (e.g. one using require, one using import) and check if they work properly.

> I'm still pretty tied up for the next couple weeks though as I'm doing two releases and the final change requests. (hence me responding at 10:30pm)

No worries. For now I have a fix on my end using [patch-package](https://www.npmjs.com/package/patch-package).

Thank you!

**Comment by WHenderson** [comment]
I hadn't seen you made a pull request. I'm in the process of doing a release with it.
Would be good if you could validate it :-D

**Comment by FunkMonkey** [comment]
> Would be good if you could validate it :-D

I will, once you have it up! :)

> I guess for testing this specific problem, one would need some test-packages (e.g. one using require, one using import) and check if they work properly.

This would probably require the `package.json`'s to contain the exports directly though (so that the symlinked monorepo packages work out of the box), instead of using `publishConfig`. Is there a specific reason, why you only add `exports` and `types` to the published packages via `publishConfig`?

**Comment by WHenderson** [comment]
FYI @FunkMonkey , I've published the changes.

> Is there a specific reason, why you only add exports and types to the published packages via publishConfig?

I was just stumbling around trying to find what worked back when I wrote the initial packages. I'm very open to doing things better, I just haven't had much time to devote to it.

The compile process also seems rather over the top. I don't think it actually needs rollup anymore, that was from an earlier requirement.

**Comment by FunkMonkey** [comment]
> FYI @FunkMonkey , I've published the changes.

Thank you very much! Works fine on my end!

> I was just stumbling around trying to find what worked back when I wrote the initial packages. I'm very open to doing things better, I just haven't had much time to devote to it.

Ah ok. Well, I never saw `publishConfig` before in any package (though I don't look that often into other package's package.json files... :) )
